# -*- coding: utf-8 -*-
"""03 - Seaborn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZxFwVApS9mDBM1CfgLmfxge3FG0KvsVe

# **Ciência de Dados para Finanças** <p>
**por: @Odemir Depieri Jr** - [Linkedin](https://www.linkedin.com/in/odemir-depieri-jr/) <p>
**por: @Ronisson Lucas Calmon da Conceição** - [Linkedin](https://www.linkedin.com/in/ronisson-lucas-calmon-da-concei%C3%A7%C3%A3o-7aa884202/) <p>
[Página do Curso](https://)

O Seaborn é uma biblioteca de visualização de dados do Python baseado no Matplotlib. Ele provê uma interface de alto nível para construção de gráficos estatísticos atrativos e informativos.
[Site Seaborn org](https://seaborn.pydata.org/)
"""

import numpy as np
import pandas as pd
import seaborn as sns

# Definir tema
sns.set_theme(style='darkgrid')

# Dados
Base_Dados = sns.load_dataset('tips')

# Varificar
Base_Dados.head()

# Renomenado as colunas
Base_Dados.rename( columns={
    'total_bill' : 'Total Conta',
    'tip' : 'Gorjeta',
    'sex' : 'Sexo',
    'smoker' : 'Fumante',
    'day' : 'Dia Semana',
    'time' : 'Periodo',
    'size' : 'Pessoas na Mesa'
 }, inplace=True )

Base_Dados.head()

"""**Gráfico relplot**"""

# Gráfico relplot
sns.relplot( x='Total Conta', y='Gorjeta', data=Base_Dados );

# Gráfico relplot
# Passando outro parametro como classe no gráfico
sns.relplot( x='Total Conta', y='Gorjeta', data=Base_Dados, hue='Sexo' );

# Gráfico de Linha com 2 Eixos
sns.relplot( x='Total Conta', y='Gorjeta', data=Base_Dados, kind='line' );

# Gráfico de Linha com 2 Eixos
sns.relplot( x='Total Conta', y='Gorjeta', data=Base_Dados, 
            kind='line', hue='Fumante' );

"""**Gráfico histplot**"""

sns.histplot( data=Base_Dados, x='Total Conta')

sns.histplot( data=Base_Dados, x='Total Conta', hue='Fumante');

"""**Gráfico barplot**"""

sns.barplot( data=Base_Dados, x='Sexo', y='Total Conta', hue='Fumante');

"""**Gráfico pairplot**"""

sns.pairplot( Base_Dados );

sns.pairplot( Base_Dados, hue='Sexo' );

sns.pairplot( Base_Dados, kind='kde' );

"""**Gráfico boxplot**"""

sns.boxplot( data=Base_Dados, x='Dia Semana', y='Total Conta');

sns.boxplot( data=Base_Dados, x='Dia Semana', y='Total Conta', hue='Sexo');

"""**Gráfico violinplot**"""

sns.violinplot( data=Base_Dados, x='Dia Semana', y='Total Conta' );

"""**Gráfico swarmplot**"""

sns.swarmplot(data=Base_Dados, x='Total Conta', y='Sexo' );

"""**Gráfico jointplot**"""

sns.jointplot( data=Base_Dados, x='Total Conta', y='Gorjeta');

